on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Configure AWS credentials with IAM Role
      uses: aws-actions/configure-aws-credentials@v4
      with:
		    inline-session-policy: >-
			     {
				      "Version": "2012-10-17",
				      "Statement": [
				          {
						          "Sid": "Statement2",
						          "Effect": "Allow",
						          "Action": [
							        "ec2:*"
						          ],
						          "Resource": [
							            "*"
						            ]
					        }
				      ]
			    }
